# Generated by Django 5.0.6 on 2026-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='अनु. नंबर')),
                ('property_number', models.CharField(max_length=50, verbose_name='मिळकत नंबर')),
                ('holder_name', models.TextField(verbose_name='मिळकत धारकाचे नाव')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='पान नंबर')),
                ('demand_gharpatii_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी घरपट्टी मागील')),
                ('demand_gharpatii_current', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी घरपट्टी चालू')),
                ('demand_gharpatii_total', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी घरपट्टी एकूण')),
                ('demand_arogya_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी आरोग्य मागील')),
                ('demand_arogya_current', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी आरोग्य चालू')),
                ('demand_arogya_total', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी आरोग्य एकूण')),
                ('demand_divabatti_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी दिवाबत्ती मागील')),
                ('demand_divabatti_current', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी दिवाबत्ती चालू')),
                ('demand_divabatti_total', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी दिवाबत्ती एकूण')),
                ('demand_paani_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी पाणीपट्टी मागील')),
                ('demand_paani_current', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी पाणीपट्टी चालू')),
                ('demand_paani_total', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी पाणीपट्टी एकूण')),
                ('demand_dand_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी 5% दंड/सूट मागील')),
                ('demand_dand_current', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी 5% दंड/सूट चालू')),
                ('demand_dand_total', models.CharField(blank=True, default='', max_length=50, verbose_name='मागणी 5% दंड/सूट एकूण')),
                ('demand_total_previous', models.CharField(blank=True, default='', max_length=50, verbose_name='एकूण मागणी मागील')),
                ('demand_total_current', models.CharField(blank=True, default='', max_length=50, verbose_name='एकूण मागणी चालू')),
                ('demand_total_ekun', models.CharField(blank=True, default='', max_length=50, verbose_name='एकूण मागणी एकूण')),
                ('receipt_before_dec31', models.CharField(blank=True, default='', max_length=100, verbose_name='३१ डिसें पूर्वी पावती क्रमांक')),
                ('receipt_after_dec31', models.CharField(blank=True, default='', max_length=100, verbose_name='पावती दिनांक')),
                ('vasuli_gharpatii', models.CharField(blank=True, default='', max_length=50, verbose_name='वसूली घरपट्टी')),
                ('vasuli_arogya', models.CharField(blank=True, default='', max_length=50, verbose_name='वसूली आरोग्य')),
                ('vasuli_divabatti', models.CharField(blank=True, default='', max_length=50, verbose_name='वसूली दिवाबत्ती')),
                ('vasuli_paani', models.CharField(blank=True, default='', max_length=50, verbose_name='वसूली पाणीपट्टी')),
                ('vasuli_dand', models.CharField(blank=True, default='', max_length=50, verbose_name='वसूली 5% दंड/सूट')),
                ('vasuli_total', models.CharField(blank=True, default='', max_length=50, verbose_name='एकूण वसूली')),
                ('yene_baki', models.CharField(blank=True, default='', max_length=50, verbose_name='येणे बाकी')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax Record',
                'verbose_name_plural': 'Tax Records',
                'ordering': ['page_number', 'id'],
            },
        ),
    ]
