# Generated by Django 5.0.6 on 2026-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='holder_phone_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
