# Generated by Django 5.0.6 on 2026-05-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_taxrecord_holder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='holder_phone_number',
            field=models.CharField(blank=True, default='0', max_length=15, verbose_name='फोन नंबर'),
        ),
    ]
