# Generated by Django 5.0.6 on 2026-05-24 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0003_alter_taxrecord_holder_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_phone_number', models.CharField(default='0', max_length=15, verbose_name='फोन नंबर')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS पाठवला')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS वेळ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_registration', to='records.taxrecord', verbose_name='मिळकत नोंद')),
            ],
            options={
                'verbose_name': 'SMS नोंदणी',
                'verbose_name_plural': 'SMS नोंदणी',
                'ordering': ['tax_record__page_number', 'tax_record__id'],
            },
        ),
    ]
