# Generated by Django 5.0.6 on 2026-05-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='नाव')),
                ('phone_number', models.CharField(max_length=15, verbose_name='फोन नंबर')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='एकूण रक्कम')),
                ('address', models.TextField(verbose_name='पत्ता')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ऑर्डर',
                'verbose_name_plural': 'ऑर्डर्स',
                'ordering': ['-created_at'],
            },
        ),
    ]
