"""
Management command: python manage.py seed_data
Seeds the database with all records from the HTML file.
Also creates a default admin user (admin/admin123) if it doesn't exist.
"""
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from records.models import TaxRecord


RECORDS = [
    # Page 1
    {
        "serial_number": "१", "property_number": "१ / ०",
        "holder_name": "कांते रूक्मिणी मनोहर", "page_number": 1,
        "demand_gharpatii_previous": "२९६", "demand_gharpatii_current": "२९६", "demand_gharpatii_total": "२९६",
        "demand_arogya_previous": "", "demand_arogya_current": "", "demand_arogya_total": "",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "२९६", "demand_total_ekun": "२९६",
        "receipt_before_dec31": "२९६", "receipt_after_dec31": "८/१९",
        "vasuli_gharpatii": "०", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "२९६", "vasuli_total": "२९६", "yene_baki": "०",
    },
    {
        "serial_number": "२", "property_number": "१ / १",
        "holder_name": "दुग्गे सुभाष गुंडाप्पा", "page_number": 1,
        "demand_gharpatii_previous": "३०२", "demand_gharpatii_current": "४०", "demand_gharpatii_total": "४०",
        "demand_arogya_previous": "", "demand_arogya_current": "", "demand_arogya_total": "",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "३८२", "demand_total_ekun": "०",
        "receipt_before_dec31": "३८२", "receipt_after_dec31": "८/१००",
        "vasuli_gharpatii": "०", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "०", "yene_baki": "३८२",
    },
    {
        "serial_number": "३", "property_number": "२ / ०",
        "holder_name": "दुग्गे राजेंद्र सुर्यकांत, दुग्गे अनिल सुर्यकांत", "page_number": 1,
        "demand_gharpatii_previous": "१४८२", "demand_gharpatii_current": "७४१", "demand_gharpatii_total": "२२२३",
        "demand_arogya_previous": "८०", "demand_arogya_current": "४०", "demand_arogya_total": "१२०",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "८२", "demand_dand_total": "८२",
        "demand_total_previous": "१७२४", "demand_total_current": "८२१", "demand_total_ekun": "२५४५",
        "receipt_before_dec31": "२५४५", "receipt_after_dec31": "२५४५",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "२५४५",
    },
    {
        "serial_number": "४", "property_number": "३ / १",
        "holder_name": "दुग्गे अनिल सुर्यकांत", "page_number": 1,
        "demand_gharpatii_previous": "४३२", "demand_gharpatii_current": "११०", "demand_gharpatii_total": "५४२",
        "demand_arogya_previous": "८०", "demand_arogya_current": "८०", "demand_arogya_total": "८०",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "३०", "demand_dand_total": "३०",
        "demand_total_previous": "६२२", "demand_total_current": "११०", "demand_total_ekun": "७३२",
        "receipt_before_dec31": "७३२", "receipt_after_dec31": "७३२",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "७३२", "vasuli_total": "७३२", "yene_baki": "७३२",
    },
    {
        "serial_number": "५", "property_number": "३ / २",
        "holder_name": "दुग्गे अनिल सुर्यकांत", "page_number": 1,
        "demand_gharpatii_previous": "३८४", "demand_gharpatii_current": "२१५", "demand_gharpatii_total": "५९९",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "२३", "demand_dand_total": "२३",
        "demand_total_previous": "४८७", "demand_total_current": "२१५", "demand_total_ekun": "७०२",
        "receipt_before_dec31": "७०२", "receipt_after_dec31": "७०२",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "७०२", "vasuli_total": "७०२", "yene_baki": "७०२",
    },
    # Page 2
    {
        "serial_number": "५", "property_number": "३ / ३",
        "holder_name": "अथणे रक्षणा अरुण", "page_number": 2,
        "demand_gharpatii_previous": "२४९", "demand_gharpatii_current": "२४९", "demand_gharpatii_total": "२४९",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "३२९", "demand_total_ekun": "३२९",
        "receipt_before_dec31": "३२९ / १०/१०", "receipt_after_dec31": "३०/०३/२०२६",
        "vasuli_gharpatii": "२४९", "vasuli_arogya": "४०", "vasuli_divabatti": "४०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "३२९", "yene_baki": "०",
    },
    {
        "serial_number": "७", "property_number": "४ / ०",
        "holder_name": "अगरे धनपाल कल्लाप्पा", "page_number": 2,
        "demand_gharpatii_previous": "५६४", "demand_gharpatii_current": "२८२", "demand_gharpatii_total": "८४६",
        "demand_arogya_previous": "८०", "demand_arogya_current": "४०", "demand_arogya_total": "१२०",
        "demand_divabatti_previous": "८०", "demand_divabatti_current": "४०", "demand_divabatti_total": "१२०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "७२४", "demand_total_current": "३६२", "demand_total_ekun": "१०८६",
        "receipt_before_dec31": "१०८६ / २०१८", "receipt_after_dec31": "२०२५",
        "vasuli_gharpatii": "७२४", "vasuli_arogya": "८०", "vasuli_divabatti": "८०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "७२४", "yene_baki": "३६२",
    },
    {
        "serial_number": "७", "property_number": "५ / ०",
        "holder_name": "अगारे श्रीमती पारीसा, अगरे अशोक पारीसा, आगरे प्रकाश पारीसा, आगरे सुरेश पारीसा", "page_number": 2,
        "demand_gharpatii_previous": "१११७", "demand_gharpatii_current": "१११७", "demand_gharpatii_total": "१११७",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "११९७", "demand_total_ekun": "११९७",
        "receipt_before_dec31": "११९७ / २/३६", "receipt_after_dec31": "२/३६",
        "vasuli_gharpatii": "१११७", "vasuli_arogya": "४०", "vasuli_divabatti": "४०",
        "vasuli_paani": "०", "vasuli_dand": "-५५९", "vasuli_total": "५५९", "yene_baki": "५५९",
    },
    {
        "serial_number": "८", "property_number": "६ / १",
        "holder_name": "अगरे कुमार गणपती", "page_number": 2,
        "demand_gharpatii_previous": "१६५६", "demand_gharpatii_current": "१६५६", "demand_gharpatii_total": "१६५६",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "१७३६", "demand_total_ekun": "१७३६",
        "receipt_before_dec31": "१७३६ / २/३६", "receipt_after_dec31": "२/३६",
        "vasuli_gharpatii": "४०", "vasuli_arogya": "४०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "-५५९", "vasuli_total": "४", "yene_baki": "४",
    },
    {
        "serial_number": "१०", "property_number": "६ / २",
        "holder_name": "अगरे कुमार गणपती", "page_number": 2,
        "demand_gharpatii_previous": "५८०", "demand_gharpatii_current": "५८०", "demand_gharpatii_total": "११६०",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "८०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "८०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "६६०", "demand_total_current": "६६०", "demand_total_ekun": "१३२०",
        "receipt_before_dec31": "१३२०", "receipt_after_dec31": "२०/०४/२०२५",
        "vasuli_gharpatii": "५८०", "vasuli_arogya": "४०", "vasuli_divabatti": "४०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "३३", "yene_baki": "३३",
    },
    # Page 3
    {
        "serial_number": "११", "property_number": "७ / ०",
        "holder_name": "आगरे उल्लास आप्पाराव", "page_number": 3,
        "demand_gharpatii_previous": "३२७६", "demand_gharpatii_current": "३२७६", "demand_gharpatii_total": "३२७६",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "३३५६", "receipt_after_dec31": "२५/०२/२०२६",
        "vasuli_gharpatii": "०", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "३३५६", "yene_baki": "०",
    },
    {
        "serial_number": "१२", "property_number": "८ / ०",
        "holder_name": "आगरे जिनेंद्र कृष्णा", "page_number": 3,
        "demand_gharpatii_previous": "११००", "demand_gharpatii_current": "२१३४", "demand_gharpatii_total": "३२३४",
        "demand_arogya_previous": "१२०", "demand_arogya_current": "४०", "demand_arogya_total": "१६०",
        "demand_divabatti_previous": "१२०", "demand_divabatti_current": "४०", "demand_divabatti_total": "१६०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "६७", "demand_dand_current": "-६७०", "demand_dand_total": "-६०३",
        "demand_total_previous": "१४०७", "demand_total_current": "१५४४", "demand_total_ekun": "२९५१",
        "receipt_before_dec31": "२९५१ / ७/१०/२०२५", "receipt_after_dec31": "३१/१२/२०२५",
        "vasuli_gharpatii": "३२३४", "vasuli_arogya": "१६०", "vasuli_divabatti": "१६०",
        "vasuli_paani": "०", "vasuli_dand": "-६०३", "vasuli_total": "१६०", "yene_baki": "०",
    },
    {
        "serial_number": "१३", "property_number": "९ / ०",
        "holder_name": "कोले श्रीपाल सुरेंद्र, कोले गुणवंती श्रीपाल", "page_number": 3,
        "demand_gharpatii_previous": "२२७१", "demand_gharpatii_current": "२२७१", "demand_gharpatii_total": "२२७१",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "२३५१", "receipt_after_dec31": "२३५१",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "०",
    },
    {
        "serial_number": "१४", "property_number": "१० / ०",
        "holder_name": "कोले संजय आण्णा, कोले शातमती महावीर, कोले शितल महावीर, कोले श्रेयास महावीर", "page_number": 3,
        "demand_gharpatii_previous": "२६९०", "demand_gharpatii_current": "२६९२", "demand_gharpatii_total": "५३८२",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "८०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "८०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "२७७० / २७७२ / ५५४२", "receipt_after_dec31": "५५४२",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "०",
    },
    {
        "serial_number": "१५", "property_number": "११ / ०",
        "holder_name": "आणुजे बाबुराव अप्पा", "page_number": 3,
        "demand_gharpatii_previous": "२४०६", "demand_gharpatii_current": "२४०६", "demand_gharpatii_total": "२४०६",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "२४८६ / ९/१६", "receipt_after_dec31": "०१/०३/२०२६",
        "vasuli_gharpatii": "०", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "८३०", "yene_baki": "०",
    },
    # Page 4
    {
        "serial_number": "१७", "property_number": "१२ / ०",
        "holder_name": "शिरगावे भाऊ तातोबा", "page_number": 4,
        "demand_gharpatii_previous": "१८५", "demand_gharpatii_current": "१६५", "demand_gharpatii_total": "३५०",
        "demand_arogya_previous": "२०", "demand_arogya_current": "२०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "२०", "demand_divabatti_current": "२०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "२२५", "demand_total_current": "२०५", "demand_total_ekun": "४३०",
        "receipt_before_dec31": "४३०", "receipt_after_dec31": "",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "४३०",
    },
    {
        "serial_number": "२८", "property_number": "१३ / ०",
        "holder_name": "शिरगावे सुरेश दत्तु", "page_number": 4,
        "demand_gharpatii_previous": "२८१", "demand_gharpatii_current": "२८१", "demand_gharpatii_total": "२८१",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "३६१", "demand_total_ekun": "३६१",
        "receipt_before_dec31": "३६१ / ९/१८", "receipt_after_dec31": "२७/०३/२०२६",
        "vasuli_gharpatii": "२८१", "vasuli_arogya": "४०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "३६१", "yene_baki": "०",
    },
    {
        "serial_number": "१९", "property_number": "१४ / १",
        "holder_name": "कोले आण्णा आप्ता", "page_number": 4,
        "demand_gharpatii_previous": "२२५३", "demand_gharpatii_current": "७८८", "demand_gharpatii_total": "३०४१",
        "demand_arogya_previous": "१९८", "demand_arogya_current": "४०", "demand_arogya_total": "२३८",
        "demand_divabatti_previous": "२४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "२८०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "२६९१", "demand_total_current": "८६८", "demand_total_ekun": "३५५९",
        "receipt_before_dec31": "३५५९ / २/६४", "receipt_after_dec31": "३०/०९/२०२५",
        "vasuli_gharpatii": "४३५", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "४३५", "yene_baki": "३१२४",
    },
    {
        "serial_number": "२०", "property_number": "१४ / २",
        "holder_name": "कोले भालचंद्र दत्तु", "page_number": 4,
        "demand_gharpatii_previous": "१७१", "demand_gharpatii_current": "१७१", "demand_gharpatii_total": "१७१",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "२५१", "demand_total_ekun": "२५१",
        "receipt_before_dec31": "२५१", "receipt_after_dec31": "",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "२५१",
    },
    # Page 5
    {
        "serial_number": "२१", "property_number": "१४ / ३",
        "holder_name": "कोले बापु बंडु", "page_number": 5,
        "demand_gharpatii_previous": "८६", "demand_gharpatii_current": "२०", "demand_gharpatii_total": "२०",
        "demand_arogya_previous": "", "demand_arogya_current": "२०", "demand_arogya_total": "२०",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "१२६ / २/१९", "receipt_after_dec31": "२५/०९/२०२५",
        "vasuli_gharpatii": "८६", "vasuli_arogya": "२०", "vasuli_divabatti": "२०",
        "vasuli_paani": "०", "vasuli_dand": "-४", "vasuli_total": "१२२", "yene_baki": "४",
    },
    {
        "serial_number": "२२", "property_number": "१४ / ५",
        "holder_name": "कोले रमेश बंडु", "page_number": 5,
        "demand_gharpatii_previous": "८६", "demand_gharpatii_current": "२०", "demand_gharpatii_total": "२०",
        "demand_arogya_previous": "", "demand_arogya_current": "२०", "demand_arogya_total": "२०",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "१२६ / ९/२१", "receipt_after_dec31": "१०/०३/२०२६",
        "vasuli_gharpatii": "८६", "vasuli_arogya": "२०", "vasuli_divabatti": "२०",
        "vasuli_paani": "०", "vasuli_dand": "-४", "vasuli_total": "१२६", "yene_baki": "०",
    },
    {
        "serial_number": "२३", "property_number": "१५ / ०",
        "holder_name": "सुर्यवंशी शानाबाई आप्पा", "page_number": 5,
        "demand_gharpatii_previous": "१२६", "demand_gharpatii_current": "०", "demand_gharpatii_total": "१२६",
        "demand_arogya_previous": "", "demand_arogya_current": "", "demand_arogya_total": "",
        "demand_divabatti_previous": "", "demand_divabatti_current": "", "demand_divabatti_total": "",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "१२६ / २/२४", "receipt_after_dec31": "३०/०९/२०२५",
        "vasuli_gharpatii": "१२६", "vasuli_arogya": "०", "vasuli_divabatti": "०",
        "vasuli_paani": "०", "vasuli_dand": "-६", "vasuli_total": "१२०", "yene_baki": "६",
    },
    {
        "serial_number": "२४", "property_number": "१६ / ०",
        "holder_name": "गोधळी वैशाली खडू", "page_number": 5,
        "demand_gharpatii_previous": "३९८", "demand_gharpatii_current": "०", "demand_gharpatii_total": "३९८",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "४७८", "receipt_after_dec31": "",
        "vasuli_gharpatii": "", "vasuli_arogya": "", "vasuli_divabatti": "",
        "vasuli_paani": "", "vasuli_dand": "", "vasuli_total": "", "yene_baki": "८०८",
    },
    {
        "serial_number": "२५", "property_number": "१७ / ०",
        "holder_name": "गोधळी पांडुरंग कृष्णा", "page_number": 5,
        "demand_gharpatii_previous": "३५१", "demand_gharpatii_current": "०", "demand_gharpatii_total": "३५१",
        "demand_arogya_previous": "४०", "demand_arogya_current": "४०", "demand_arogya_total": "४०",
        "demand_divabatti_previous": "४०", "demand_divabatti_current": "४०", "demand_divabatti_total": "४०",
        "demand_paani_previous": "", "demand_paani_current": "", "demand_paani_total": "",
        "demand_dand_previous": "", "demand_dand_current": "", "demand_dand_total": "",
        "demand_total_previous": "०", "demand_total_current": "०", "demand_total_ekun": "०",
        "receipt_before_dec31": "४३१", "receipt_after_dec31": "१६/०३/२०२६",
        "vasuli_gharpatii": "३५१", "vasuli_arogya": "४०", "vasuli_divabatti": "४०",
        "vasuli_paani": "०", "vasuli_dand": "०", "vasuli_total": "४३१", "yene_baki": "०",
    },
]


class Command(BaseCommand):
    help = 'Seed the database with tax records from the HTML file and create a default admin user'

    def handle(self, *args, **options):
        # Create default user
        if not User.objects.filter(username='admin').exists():
            user = User.objects.create_superuser(
                username='admin',
                password='admin123',
                email='admin@grampanchayat.gov.in',
                first_name='Admin',
                last_name='User'
            )
            Token.objects.get_or_create(user=user)
            self.stdout.write(self.style.SUCCESS('✓ Created admin user (username: admin, password: admin123)'))
        else:
            self.stdout.write(self.style.WARNING('ℹ Admin user already exists'))

        # Seed tax records
        TaxRecord.objects.all().delete()
        created_count = 0
        for record_data in RECORDS:
            TaxRecord.objects.create(**record_data)
            created_count += 1

        self.stdout.write(self.style.SUCCESS(f'✓ Seeded {created_count} tax records'))
        self.stdout.write(self.style.SUCCESS('✓ Database ready! Run: python manage.py runserver'))
