# Generated by Django 5.0.6 on 2026-05-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(max_length=50, unique=True, verbose_name='SMS ID')),
                ('description1', models.TextField(blank=True, default='', verbose_name='वर्णन १')),
                ('variable1', models.CharField(blank=True, default='', max_length=100, verbose_name='चल १')),
                ('description2', models.TextField(blank=True, default='', verbose_name='वर्णन २')),
                ('variable2', models.CharField(blank=True, default='', max_length=100, verbose_name='चल २')),
                ('description3', models.TextField(blank=True, default='', verbose_name='वर्णन ३')),
                ('variable3', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ३')),
                ('description4', models.TextField(blank=True, default='', verbose_name='वर्णन ४')),
                ('variable4', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ४')),
                ('description5', models.TextField(blank=True, default='', verbose_name='वर्णन ५')),
                ('variable5', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ५')),
                ('description6', models.TextField(blank=True, default='', verbose_name='वर्णन ६')),
                ('variable6', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ६')),
                ('description7', models.TextField(blank=True, default='', verbose_name='वर्णन ७')),
                ('variable7', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ७')),
                ('description8', models.TextField(blank=True, default='', verbose_name='वर्णन ८')),
                ('variable8', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ८')),
                ('description9', models.TextField(blank=True, default='', verbose_name='वर्णन ९')),
                ('variable9', models.CharField(blank=True, default='', max_length=100, verbose_name='चल ९')),
                ('description10', models.TextField(blank=True, default='', verbose_name='वर्णन १०')),
                ('variable10', models.CharField(blank=True, default='', max_length=100, verbose_name='चल १०')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['sms_id'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_message', models.TextField(verbose_name='पाठवलेला संदेश')),
                ('phone_number', models.CharField(max_length=15, verbose_name='फोन नंबर')),
                ('tax_record_id', models.IntegerField(blank=True, null=True, verbose_name='TaxRecord ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=20, verbose_name='अनु. नंबर')),
                ('holder_name', models.CharField(blank=True, default='', max_length=300, verbose_name='धारकाचे नाव')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('gateway_response', models.TextField(blank=True, default='', verbose_name='Gateway Response')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='पाठवल्याची वेळ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='messaging.smstemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
